sudo: false
language: node_js
node_js:
  - "stable"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
cache:
  directories:
    - node_modules
script: "npm run test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
